/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cloudmedical.telas;

import br.com.cloudmedical.classes.Configuracao;
import br.com.cloudmedical.classes.ManterMedicos;
import br.com.cloudmedical.classes.Relatorios;
import br.com.cloudmedical.classes.UsuarioClasse;
import br.com.cloudmedical.classes.Constantes;
import cloudmedical.ConexaoBanco;
import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Debug
 */
public class TelaPrincipal extends javax.swing.JFrame {
    Locale locale = new Locale("pt", "BR");
    Calendar cal = Calendar.getInstance(locale);
    Date data;
    Medicos medico;
    BuscaMedico buscaMedico;
    ConexaoBanco banco;
    DefaultListModel lista = new DefaultListModel();
    UsuarioClasse user;
    Relatorios rel;

    private int idUsuarioLogado;
    private String nomeUsuarioLogado;

    public int getIdUsuarioLogado() {
        return idUsuarioLogado;
    }

    public void setIdUsuarioLogado(int idUsuarioLogado) {
        this.idUsuarioLogado = idUsuarioLogado;
    }

    public String getNomeUsuarioLogado() {
        return nomeUsuarioLogado;
    }

    public void setNomeUsuarioLogado(String nomeUsuarioLogado) {
        this.nomeUsuarioLogado = nomeUsuarioLogado;
    }
    
    

    /**
     * Creates new form telaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        preencheLabelsPanelBaixo();
        primeiroUsuario();
        desabilitaMenus();
        verificaConfiguracao();
//        tamanhoMenus();
    }
    
    public TelaPrincipal(int idUsuarioLogado, String nomeUsuarioLogado){
        this.idUsuarioLogado = idUsuarioLogado;
        this.nomeUsuarioLogado = nomeUsuarioLogado;
    }
    
    public void tamanhoMenus(){
        Dimension dimensao = new Dimension();
        dimensao.setSize(150, 30);
        
        menuArquivo.setPreferredSize(dimensao);
        subMenuSair.setPreferredSize(dimensao);
        menuSobre.setPreferredSize(dimensao);
        
    }
    
    public void verificaConfiguracao(){
        Configuracao config = new Configuracao();
        
        if(!config.retornaArquivo()){
//            PrimeiroUsuario primeiro = new PrimeiroUsuario(this, true);
//            primeiro.setTitle("Primeiro Usuário");
//            primeiro.setLocationRelativeTo(primeiro);
//            primeiro.setVisible(true);
            ConfiguracaoCloud cloud = new ConfiguracaoCloud(this, true);
            cloud.setTitle("Configuração Inicial");
            cloud.setLocationRelativeTo(cloud);
            cloud.setVisible(true);
        }
        
    }
    
    public void primeiroUsuario(){
        user = new UsuarioClasse();
        if(user.verificaExisteUsuario()){//retorna null
            PrimeiroUsuario primeiro = new PrimeiroUsuario(this, true);
            primeiro.setTitle("Primeiro Usuário");
            primeiro.setLocationRelativeTo(primeiro);
            primeiro.setVisible(true);            
        }
    }
    
    public void preencheLabelsPanelBaixo(){
        labelConexao.setVisible(false);
        banco = new ConexaoBanco();
        
        int dia = cal.get(Calendar.DAY_OF_MONTH);
        int mes = cal.get(Calendar.MONTH) + 1;
        int ano = cal.get(Calendar.YEAR);
        String mesLongo = null;
        
        if(mes < 10){
            mesLongo = "0" + mes;
        }else{
            mesLongo = String.valueOf(mes);
        }
        
        String dataHoje = dia + "/" + mesLongo + "/" + ano;
        labelSistema.setText(Constantes.versao);
        labelDeveloper.setText(Constantes.autor);
        labelExclusivo.setText(Constantes.empresa);
        labelData.setText("Data: " + dataHoje);
//        labelConexao.setText("Conectando o banco de dados...");
//        banco.getConnection();
        if(banco.getConnection() != null){
            labelConexao.setVisible(true);
        }else{
            labelConexao.setVisible(false);
        }
    }
    
    public void sair(){
        System.exit(0);
    }
    
    public void adicionarElementos(String content){
        lista.addElement("\n\n- " + content);
        listaProcessos.setModel(lista);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        btMedical = new javax.swing.JButton();
        separadorButtons = new javax.swing.JToolBar.Separator();
        btBuscaMedico = new javax.swing.JButton();
        panelFundo = new javax.swing.JPanel();
        labelImage = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProcessos = new javax.swing.JList();
        panelTeclas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaComandos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        panelBaixo = new javax.swing.JPanel();
        labelConexao = new javax.swing.JLabel();
        labelDeveloper = new javax.swing.JLabel();
        labelSistema = new javax.swing.JLabel();
        labelExclusivo = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        subMenuLogin = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        subMenuTelefones = new javax.swing.JMenuItem();
        subMenuMedicos = new javax.swing.JMenuItem();
        subMenuBuscaMedico = new javax.swing.JMenuItem();
        subMenuTerceirizados = new javax.swing.JMenuItem();
        separador = new javax.swing.JPopupMenu.Separator();
        subMenuLogoff = new javax.swing.JMenuItem();
        subMenuSair = new javax.swing.JMenuItem();
        menuFinanceiro = new javax.swing.JMenu();
        subMenuPagamentos = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        subMenuRelMedicos = new javax.swing.JMenuItem();
        subMenuRelTerceirizados = new javax.swing.JMenuItem();
        separador3 = new javax.swing.JPopupMenu.Separator();
        subMenuRelPagtos = new javax.swing.JMenuItem();
        menuFerramentas = new javax.swing.JMenu();
        subMenuUsuarios = new javax.swing.JMenuItem();
        subMenuTpPagtos = new javax.swing.JMenuItem();
        subMenuTeclas = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        subMenuSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        toolBar.setBackground(new java.awt.Color(255, 255, 255));
        toolBar.setFloatable(false);
        toolBar.setRollover(true);

        btMedical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudmedical/images/iconmedico24x24.png"))); // NOI18N
        btMedical.setFocusable(false);
        btMedical.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMedical.setMaximumSize(new java.awt.Dimension(60, 50));
        btMedical.setPreferredSize(new java.awt.Dimension(50, 50));
        btMedical.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMedicalActionPerformed(evt);
            }
        });
        toolBar.add(btMedical);
        toolBar.add(separadorButtons);

        btBuscaMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudmedical/images/buscaMedico.png"))); // NOI18N
        btBuscaMedico.setFocusable(false);
        btBuscaMedico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBuscaMedico.setMaximumSize(new java.awt.Dimension(60, 50));
        btBuscaMedico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btBuscaMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaMedicoActionPerformed(evt);
            }
        });
        toolBar.add(btBuscaMedico);

        panelFundo.setBackground(new java.awt.Color(255, 255, 255));
        panelFundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        labelImage.setBackground(new java.awt.Color(255, 255, 255));
        labelImage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudmedical/images/medicina.png"))); // NOI18N

        labelData.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelData.setText("jLabel1");

        jScrollPane1.setBorder(null);

        listaProcessos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jScrollPane1.setViewportView(listaProcessos);

        panelTeclas.setBackground(new java.awt.Color(255, 255, 255));
        panelTeclas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        listaComandos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu", "Tecla Atalho"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(listaComandos);
        if (listaComandos.getColumnModel().getColumnCount() > 0) {
            listaComandos.getColumnModel().getColumn(0).setResizable(false);
            listaComandos.getColumnModel().getColumn(0).setPreferredWidth(250);
            listaComandos.getColumnModel().getColumn(1).setResizable(false);
            listaComandos.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        javax.swing.GroupLayout panelTeclasLayout = new javax.swing.GroupLayout(panelTeclas);
        panelTeclas.setLayout(panelTeclasLayout);
        panelTeclasLayout.setHorizontalGroup(
            panelTeclasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTeclasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTeclasLayout.setVerticalGroup(
            panelTeclasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTeclasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelFundoLayout = new javax.swing.GroupLayout(panelFundo);
        panelFundo.setLayout(panelFundoLayout);
        panelFundoLayout.setHorizontalGroup(
            panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelData)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFundoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(panelFundoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelTeclas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelFundoLayout.setVerticalGroup(
            panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFundoLayout.createSequentialGroup()
                        .addComponent(labelData, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(panelFundoLayout.createSequentialGroup()
                        .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(panelTeclas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        labelConexao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudmedical/images/world.png"))); // NOI18N
        labelConexao.setToolTipText("Banco de dados conectado!");

        labelDeveloper.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelDeveloper.setText("jLabel1");

        labelSistema.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelSistema.setText("jLabel1");

        labelExclusivo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelExclusivo.setText("jLabel1");

        javax.swing.GroupLayout panelBaixoLayout = new javax.swing.GroupLayout(panelBaixo);
        panelBaixo.setLayout(panelBaixoLayout);
        panelBaixoLayout.setHorizontalGroup(
            panelBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaixoLayout.createSequentialGroup()
                .addComponent(labelSistema)
                .addGap(162, 162, 162)
                .addComponent(labelDeveloper)
                .addGap(193, 193, 193)
                .addComponent(labelExclusivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelConexao)
                .addContainerGap())
        );
        panelBaixoLayout.setVerticalGroup(
            panelBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaixoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBaixoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(panelBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDeveloper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelExclusivo)))
                    .addComponent(labelConexao, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        menu.setBackground(new java.awt.Color(51, 102, 255));

        menuArquivo.setText("Arquivo");
        menuArquivo.setPreferredSize(new java.awt.Dimension(70, 19));

        subMenuLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        subMenuLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudmedical/images/mobile_group_icon_n.png"))); // NOI18N
        subMenuLogin.setText("  Login");
        subMenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuLoginActionPerformed(evt);
            }
        });
        menuArquivo.add(subMenuLogin);
        menuArquivo.add(jSeparator2);

        subMenuTelefones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        subMenuTelefones.setText("  Telefones");
        subMenuTelefones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuTelefonesActionPerformed(evt);
            }
        });
        menuArquivo.add(subMenuTelefones);

        subMenuMedicos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        subMenuMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudmedical/images/iconmedico24x24.png"))); // NOI18N
        subMenuMedicos.setText("  Médicos");
        subMenuMedicos.setPreferredSize(new java.awt.Dimension(150, 25));
        subMenuMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuMedicosActionPerformed(evt);
            }
        });
        menuArquivo.add(subMenuMedicos);

        subMenuBuscaMedico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        subMenuBuscaMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudmedical/images/buscaMedico.png"))); // NOI18N
        subMenuBuscaMedico.setText("  Busca de Médicos");
        subMenuBuscaMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuBuscaMedicoActionPerformed(evt);
            }
        });
        menuArquivo.add(subMenuBuscaMedico);

        subMenuTerceirizados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        subMenuTerceirizados.setText("  Terceirizados");
        subMenuTerceirizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuTerceirizadosActionPerformed(evt);
            }
        });
        menuArquivo.add(subMenuTerceirizados);
        menuArquivo.add(separador);

        subMenuLogoff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        subMenuLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudmedical/images/icon-people.png"))); // NOI18N
        subMenuLogoff.setText("  Logoff");
        subMenuLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuLogoffActionPerformed(evt);
            }
        });
        menuArquivo.add(subMenuLogoff);

        subMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        subMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudmedical/images/shuttdown.png"))); // NOI18N
        subMenuSair.setText("  Sair");
        subMenuSair.setPreferredSize(new java.awt.Dimension(150, 25));
        subMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuSairActionPerformed(evt);
            }
        });
        menuArquivo.add(subMenuSair);

        menu.add(menuArquivo);

        menuFinanceiro.setText("Financeiro");
        menuFinanceiro.setPreferredSize(new java.awt.Dimension(70, 19));

        subMenuPagamentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        subMenuPagamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudmedical/images/calculadoraIcon.png"))); // NOI18N
        subMenuPagamentos.setText("Pagamentos");
        subMenuPagamentos.setPreferredSize(new java.awt.Dimension(150, 25));
        subMenuPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuPagamentosActionPerformed(evt);
            }
        });
        menuFinanceiro.add(subMenuPagamentos);

        menu.add(menuFinanceiro);

        menuRelatorios.setText("Relatórios");
        menuRelatorios.setPreferredSize(new java.awt.Dimension(70, 19));

        subMenuRelMedicos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        subMenuRelMedicos.setText("Médicos");
        subMenuRelMedicos.setPreferredSize(new java.awt.Dimension(150, 25));
        subMenuRelMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuRelMedicosActionPerformed(evt);
            }
        });
        menuRelatorios.add(subMenuRelMedicos);

        subMenuRelTerceirizados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        subMenuRelTerceirizados.setText("Terceirizados");
        subMenuRelTerceirizados.setPreferredSize(new java.awt.Dimension(150, 25));
        menuRelatorios.add(subMenuRelTerceirizados);
        menuRelatorios.add(separador3);

        subMenuRelPagtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        subMenuRelPagtos.setText("Pagamentos");
        subMenuRelPagtos.setPreferredSize(new java.awt.Dimension(150, 25));
        menuRelatorios.add(subMenuRelPagtos);

        menu.add(menuRelatorios);

        menuFerramentas.setText("Ferramentas");

        subMenuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        subMenuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudmedical/images/mobile_group_icon_n.png"))); // NOI18N
        subMenuUsuarios.setText("Usuários");
        subMenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuUsuariosActionPerformed(evt);
            }
        });
        menuFerramentas.add(subMenuUsuarios);

        subMenuTpPagtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        subMenuTpPagtos.setText("Tipos de Pagamentos");
        menuFerramentas.add(subMenuTpPagtos);

        subMenuTeclas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        subMenuTeclas.setText("Teclas de Atalho");
        subMenuTeclas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuTeclasActionPerformed(evt);
            }
        });
        menuFerramentas.add(subMenuTeclas);

        menu.add(menuFerramentas);

        menuSobre.setText("Sobre");
        menuSobre.setPreferredSize(new java.awt.Dimension(70, 19));

        subMenuSistema.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        subMenuSistema.setText("Sistema");
        menuSobre.add(subMenuSistema);

        menu.add(menuSobre);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(panelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBaixo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuSairActionPerformed
        
        adicionarElementos("Iniciando o processo de saída...");
        
        if(JOptionPane.showConfirmDialog(null, "Deseja sair?", "SAIR", JOptionPane.YES_NO_OPTION) == 0){
            sair();
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_subMenuSairActionPerformed

    private void btMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMedicalActionPerformed

        medico = new Medicos(this, true);
        medico.setTitle("Cadastro de Médicos");
        medico.setCodUsuario(this.getIdUsuarioLogado());
        medico.setLocationRelativeTo(medico);
        medico.setVisible(true);

    }//GEN-LAST:event_btMedicalActionPerformed

    private void subMenuMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuMedicosActionPerformed
        btMedicalActionPerformed(evt);
        
    }//GEN-LAST:event_subMenuMedicosActionPerformed

    private void btBuscaMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaMedicoActionPerformed
        buscaMedico = new BuscaMedico(this, true);
        buscaMedico.setTitle("Busca de Médicos");
        buscaMedico.setLocationRelativeTo(buscaMedico);
        buscaMedico.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_btBuscaMedicoActionPerformed

    private void subMenuBuscaMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuBuscaMedicoActionPerformed
        btBuscaMedicoActionPerformed(evt);
        
// TODO add your handling code here:
    }//GEN-LAST:event_subMenuBuscaMedicoActionPerformed

    private void subMenuLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuLogoffActionPerformed
        logoff();
        
// TODO add your handling code here:
    }//GEN-LAST:event_subMenuLogoffActionPerformed

    private void subMenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuUsuariosActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_subMenuUsuariosActionPerformed

    private void subMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuLoginActionPerformed
        Usuarios telaUser = new Usuarios(this, true);
        telaUser.setTitle("LOGIN");
        telaUser.setLocationRelativeTo(telaUser);
        telaUser.setVisible(true);
        
        if(telaUser.isAutoriza()){
            habilitaMenus();
            adicionarElementos("Bem-vindo, " + telaUser.getLogin());
            this.idUsuarioLogado = telaUser.getIdUsuario();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_subMenuLoginActionPerformed

    private void subMenuPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuPagamentosActionPerformed
        Pagamento pagto = new Pagamento(this, true);
        
        pagto.setTitle("Pagamentos");
        pagto.setLocationRelativeTo(pagto);
        pagto.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_subMenuPagamentosActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    

// TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void subMenuTerceirizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuTerceirizadosActionPerformed
        Terceirizados terceiros = new Terceirizados(this, true);
        
        terceiros.setTitle("Terceirizados");
        terceiros.setLocationRelativeTo(terceiros);
        terceiros.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_subMenuTerceirizadosActionPerformed

    private void subMenuTeclasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuTeclasActionPerformed
        teclaAtalho();
        
// TODO add your handling code here:
    }//GEN-LAST:event_subMenuTeclasActionPerformed

    private void subMenuTelefonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuTelefonesActionPerformed

        Telefones telefone = new Telefones(this, true);
        
        telefone.setTitle("Telefones");
        telefone.setLocationRelativeTo(telefone);
        telefone.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_subMenuTelefonesActionPerformed

    private void subMenuRelMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuRelMedicosActionPerformed
        adicionarElementos("=================================");
        adicionarElementos("Abrindo o relatório de médicos...");
        
// TODO add your handling code here:
    }//GEN-LAST:event_subMenuRelMedicosActionPerformed

    public void teclaAtalho(){
        DefaultTableModel tabela = (DefaultTableModel) listaComandos.getModel();

        if(panelTeclas.isVisible()){
            panelTeclas.setVisible(false);
            tabela.getDataVector().removeAllElements();
            listaComandos.setModel(tabela);
            subMenuTeclas.setBackground(null);
        }else{
            panelTeclas.setVisible(true);
            tabela.addRow(new String[]{"ARQUIVO", "====="});
            tabela.addRow(new String[]{"     Login", "Ctrl + L"});
            tabela.addRow(new String[]{"     Telefones", "Ctrl + Shift + T"});
            tabela.addRow(new String[]{"     Médicos", "Ctrl + M"});
            tabela.addRow(new String[]{"     Busca de Médicos", "Ctrl + B"});
            tabela.addRow(new String[]{"     Terceirizados", "Ctrl + T"});
            tabela.addRow(new String[]{"     Logoff", "Ctrl + F4"});
            tabela.addRow(new String[]{"     Sair", "F4"});
            tabela.addRow(new String[]{"FINANCEIRO", "====="});
            tabela.addRow(new String[]{"     Pagamentos", "Ctrl + P"});
            tabela.addRow(new String[]{"RELATÓRIOS", "====="});
            tabela.addRow(new String[]{"     Médicos", "Ctrl + Alt + M"});
            tabela.addRow(new String[]{"     Terceirizados", "Ctrl + Alt + T"});
            tabela.addRow(new String[]{"     Pagamentos", "Ctrl + Alt + P"});
            tabela.addRow(new String[]{"FERRAMENTAS", "====="});
            tabela.addRow(new String[]{"     Usuários", "Ctrl + U"});
            tabela.addRow(new String[]{"     Tipos de Pagamentos", "Ctrl + Shift + P"});
            tabela.addRow(new String[]{"     Teclas de Atalho", "Shift + A"});
            tabela.addRow(new String[]{"SOBRE", "====="});
            tabela.addRow(new String[]{"     Sistema", "Ctrl + F1"});
            listaComandos.setModel(tabela);
            subMenuTeclas.setBackground(Color.LIGHT_GRAY);//getHSBColor(240, 240, 240)
            }
        
    }
    
    
    public void logoff(){
        desabilitaMenus();
        adicionarElementos("Você efetuou o logoff com sucesso.");
    }
    
    public void desabilitaMenus(){
        menuFinanceiro.setEnabled(false);
        menuFerramentas.setEnabled(false);
        menuRelatorios.setEnabled(false);
        subMenuTelefones.setEnabled(false);
        subMenuMedicos.setEnabled(false);
        subMenuBuscaMedico.setEnabled(false);
        subMenuTerceirizados.setEnabled(false);
        subMenuLogoff.setEnabled(false);
        subMenuLogin.setEnabled(true);
        panelTeclas.setVisible(false);
        btMedical.setEnabled(false);
        btBuscaMedico.setEnabled(false);
    }
    public void habilitaMenus(){
        menuFinanceiro.setEnabled(true);
        menuFerramentas.setEnabled(true);
        menuRelatorios.setEnabled(true);
        subMenuTelefones.setEnabled(true);
        subMenuMedicos.setEnabled(true);
        subMenuBuscaMedico.setEnabled(true);
        subMenuTerceirizados.setEnabled(true);
        subMenuLogoff.setEnabled(true);
        subMenuLogin.setEnabled(false);
        btMedical.setEnabled(true);
        btBuscaMedico.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscaMedico;
    private javax.swing.JButton btMedical;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel labelConexao;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelDeveloper;
    private javax.swing.JLabel labelExclusivo;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelSistema;
    private javax.swing.JTable listaComandos;
    private javax.swing.JList listaProcessos;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuFerramentas;
    private javax.swing.JMenu menuFinanceiro;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JPanel panelBaixo;
    private javax.swing.JPanel panelFundo;
    private javax.swing.JPanel panelTeclas;
    private javax.swing.JPopupMenu.Separator separador;
    private javax.swing.JPopupMenu.Separator separador3;
    private javax.swing.JToolBar.Separator separadorButtons;
    private javax.swing.JMenuItem subMenuBuscaMedico;
    private javax.swing.JMenuItem subMenuLogin;
    private javax.swing.JMenuItem subMenuLogoff;
    private javax.swing.JMenuItem subMenuMedicos;
    private javax.swing.JMenuItem subMenuPagamentos;
    private javax.swing.JMenuItem subMenuRelMedicos;
    private javax.swing.JMenuItem subMenuRelPagtos;
    private javax.swing.JMenuItem subMenuRelTerceirizados;
    private javax.swing.JMenuItem subMenuSair;
    private javax.swing.JMenuItem subMenuSistema;
    private javax.swing.JMenuItem subMenuTeclas;
    private javax.swing.JMenuItem subMenuTelefones;
    private javax.swing.JMenuItem subMenuTerceirizados;
    private javax.swing.JMenuItem subMenuTpPagtos;
    private javax.swing.JMenuItem subMenuUsuarios;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables


}
